# Generated by Django 5.0.6 on 2024-08-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPendingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField(verbose_name='Fecha de expiracion')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.ticket', verbose_name='Boleta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.clientinfo', verbose_name='Cliente')),
            ],
        ),
    ]
