# Generated by Django 5.0.6 on 2024-08-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangopwa", "0002_ticketpendingpurchase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketpendingpurchase",
            options={
                "verbose_name": "Compra Pendiente",
                "verbose_name_plural": "Compras Pendientes",
            },
        ),
    ]
