# Generated by Django 5.0.6 on 2024-08-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangopwa", "0003_alter_ticketpendingpurchase_options"),
        ("djangopwa", "0003_whatsapp_alter_ticketpendingpurchase_options_and_more"),
    ]

    operations = []
