# Generated by Django 5.0.6 on 2024-09-01 07:26

import cloudinary.models
import django.db.models.deletion
import djangopwa.cloudinary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0003_whatsapp_alter_ticketpendingpurchase_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchased',
            name='purchased_reference',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='purchase_reference',
            field=models.CharField(default='', max_length=200, verbose_name='Referencia de compra'),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase_reference',
            field=models.CharField(default='', max_length=200, verbose_name='Referencia de compra'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', max_length=200, verbose_name='ID de transaccion'),
        ),
        migrations.AddField(
            model_name='ticketpendingpurchase',
            name='purchase_reference',
            field=models.CharField(default='', max_length=200, verbose_name='Referencia de compra'),
        ),
        migrations.AddField(
            model_name='ticketpendingpurchase',
            name='transaction_id',
            field=models.CharField(default='', max_length=200, verbose_name='ID de transaccion'),
        ),
        migrations.AddField(
            model_name='ticketpurchased',
            name='purchase_reference',
            field=models.CharField(default='', max_length=200, verbose_name='Referencia de compra'),
        ),
        migrations.AddField(
            model_name='ticketpurchased',
            name='transaction_id',
            field=models.CharField(default='', max_length=200, verbose_name='ID de transaccion'),
        ),
        migrations.AddField(
            model_name='ticketreserved',
            name='purchase_reference',
            field=models.CharField(default='', max_length=200, verbose_name='Referencia de compra'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='', max_length=32, verbose_name='Metodo de pago'),
        ),
        migrations.CreateModel(
            name='BillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[djangopwa.cloudinary.file_validation], verbose_name='foto')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.lottery')),
            ],
            options={
                'verbose_name': 'Imagen de factura',
                'verbose_name_plural': 'Imagenes de facturas',
            },
        ),
    ]
