# Generated by Django 5.0.6 on 2024-09-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangopwa", "0004_merge_20240818_1630"),
        ("djangopwa", "0004_remove_ticketpurchased_purchased_reference_and_more"),
    ]

    operations = []
