# Generated by Django 5.0.6 on 2024-09-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0004_remove_ticketpurchased_purchased_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpendingpurchase',
            name='transaction_id',
        ),
    ]
