# Generated by Django 5.0.6 on 2024-09-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangopwa", "0005_merge_20240902_1401"),
        ("djangopwa", "0005_remove_ticketpendingpurchase_transaction_id"),
    ]

    operations = []
