# Generated by Django 5.0.6 on 2024-09-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0005_remove_ticketpendingpurchase_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketpendingpurchase',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='ticketpurchased',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='ticketreserved',
            old_name='user',
            new_name='client',
        ),
    ]
