# Generated by Django 5.0.6 on 2024-09-19 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0006_rename_user_ticketpendingpurchase_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketWithPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_reference', models.CharField(default='', max_length=200, verbose_name='Referencia de compra')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.clientinfo', verbose_name='Cliente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.ticket', verbose_name='Boleta')),
            ],
            options={
                'verbose_name': 'Boleta con abono',
                'verbose_name_plural': 'Boletas con abono',
            },
        ),
    ]
