# Generated by Django 5.0.6 on 2024-09-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0007_ticketwithpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase_reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referencia de compra'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de transacción'),
        ),
    ]
