# Generated by Django 5.0.6 on 2024-09-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0011_alter_billimage_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpendingpurchase',
            name='purchase_reference',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Referencia de compra'),
        ),
        migrations.AlterField(
            model_name='ticketpurchased',
            name='purchase_reference',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Referencia de compra'),
        ),
        migrations.AlterField(
            model_name='ticketreserved',
            name='purchase_reference',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Referencia de compra'),
        ),
        migrations.AlterField(
            model_name='ticketwithpayment',
            name='purchase_reference',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Referencia de compra'),
        ),
    ]
