# Generated by Django 5.0.6 on 2024-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0012_alter_ticketpendingpurchase_purchase_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
