# Generated by Django 5.0.6 on 2024-09-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangopwa", "0006_merge_20240918_1330"),
        ("djangopwa", "0013_alter_payment_amount"),
    ]

    operations = []
