# Generated by Django 5.0.6 on 2024-09-21 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0014_merge_20240920_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketassignment',
            options={'verbose_name': 'Ticket assignment', 'verbose_name_plural': 'Ticket assignments'},
        ),
        migrations.AddField(
            model_name='ticketassignment',
            name='individual_tickets',
            field=models.ManyToManyField(blank=True, to='djangopwa.ticket', verbose_name='Individual tickets'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='end_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.lottery', verbose_name='lottery'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='start_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
    ]
