# Generated by Django 5.0.6 on 2024-09-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopwa', '0015_alter_ticketassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketassignment',
            options={'verbose_name': 'Asignar boleta', 'verbose_name_plural': 'Asignación boletas'},
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='asignado a'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='end_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='hasta'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='individual_tickets',
            field=models.ManyToManyField(blank=True, to='djangopwa.ticket', verbose_name='Boletas individuales'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangopwa.lottery', verbose_name='rifa'),
        ),
        migrations.AlterField(
            model_name='ticketassignment',
            name='start_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='desde'),
        ),
    ]
